config/routes.rb
CatsProject::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      post "approve" => 'cat_rental_requests#approve'
      post "deny" => 'cat_rental_requests#deny'
    end
  end
  resources :users do
    resource :session, except: [:new, :create]
  end

  resource :session, only: [:new, :create]

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true

  validates_numericality_of :age
  validates_inclusion_of :sex, in: %w( M F )
  validates_inclusion_of :color, in: %w( Black Brown White Tabby Tie-Dye )

  has_many(
    :requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
    )

    belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
    )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  before_validation do
    self.status ||= "PENDING"
  end

  validates :status, inclusion: { in: %w( PENDING APPROVED DENIED ) }
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :cat_id, inclusion: { in: Cat.pluck(:id) }

  validate :no_overlapping_requests

  belongs_to(
  :cat,
  class_name: "Cat",
  foreign_key: :cat_id,
  primary_key: :id
  )

  def approve!
    self.status = "APPROVED"
    self.save!
    transaction do
      overlapping_requests("PENDING").each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end


  private

  def no_overlapping_requests
    requests = overlapping_requests("APPROVED")
    unless requests.empty? || self.status != "APPROVED"
      requests.each do |request|
        errors[:start_date] << "Conflicts with another start date"
        errors[:end_date] << "Conflicts with another end date"
      end
    end
  end

  def overlapping_requests(status)
    CatRentalRequest.where(cat_id: self.cat_id, status: status).
    where("start_date <= ? AND end_date >= ?", self.end_date, self.start_date).
    where("id != ?", self.id)
  end


end

app/models/user.rb
require 'SecureRandom'

class User < ActiveRecord::Base
  attr_accessible :user_name, :session_token, :password
  attr_reader :password

  before_validation do
    self.session_token ||= User.generate_session_token
  end

  validates :password_digest, :user_name, :session_token, presence: true
  validates :user_name, :session_token, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many(
  :cats,
  class_name: "Cat",
  foreign_key: :user_id,
  primary_key: :id)

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    session_token = User.generate_session_token
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    user.is_password?(password) ? user : nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include SessionHelper
  protect_from_forgery
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    before_filter :check_owner, only: [:edit, :approve, :deny]

  def new
    @cats = Cat.all
  end

  def create
    @cat_rental_request = CatRentalRequest.new(params[:cat_rental_request])

    if @cat_rental_request.save
      redirect_to cats_url
    else
      flash.notice = "Save failed"

      redirect_to :back
    end
  end

  def approve
    rent = CatRentalRequest.find(params[:id])
    rent.approve!
    redirect_to cat_url(rent.cat_id)
  end

  def deny
    rent = CatRentalRequest.find(params[:id])
    rent.deny!
    redirect_to cat_url(rent.cat_id)
  end

  def check_owner
    @cat = CatRentalRequest.find(params[:id]).cat
    unless current_user.id == @cat.user_id
      flash.notice = "Can only confirm/deny reservations for your own cat"
      redirect_to cats_url
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :check_owner, only: [:edit]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.where(id: params[:id]).includes(:requests).first
  end

  def new
    unless self.current_user
      flash.notice = "Must be logged in to create a cat"
      redirect_to new_session_url
    end
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(params[:cat])

    if @cat.save
      redirect_to cat_url @cat.id
    else
      flash.notice = "Update failed"
      redirect_to cats_url
    end

  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def create
    @cat = current_user.cats.build(params[:cat])

  #  params[:cat][:user_id] = self.current_user.id
     #@cat = Cat.new(params[:cat])

    if @cat.save
      redirect_to cat_url @cat.id
    else
      flash.notice = "Save failed"
      redirect_to cats_url
    end
  end

  def destroy
    @cat = Cat.find(params[:id])

    if @cat.destroy
      redirect_to cats_url
    else
      flash.notice = "Delete failed"
      redirect_to cats_url
    end
  end

  def check_owner
    @cat = Cat.find(params[:id])
    unless self.current_user.id == @cat.user_id
      flash.notice = "Can only edit your own cat"
      redirect_to cats_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
include SessionHelper
  def new

  end

  def create
    user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password])

    if user.nil?
      flash.notice = "Save failed"
      render :back
    else
      self.current_user = user
      redirect_to cats_url
      flash.notice = "Welcome back #{user.user_name}"
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(params[:user])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to cats_url
    else
      flash.notice = "Save failed"
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logout_current_user!
    @current_user = User.find(params[:user_id])
    @current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>"  method="post">

  <h1>  Cat Selections! </h1>

  <label>
    Please Select a Cat
    <select name="cat_rental_request[cat_id]">
      <option value="">Select a cat</option>
      <% @cats.each do |cat| %>
        <option value="<%=cat.id%>"><%= cat.name %></option>
      <% end %>
    </select>
  </label>
  <br>
  <label>
    Start date:
    <input type="date" name="cat_rental_request[start_date]">
  </label>
  <label>
    End date:
    <input type="date" name="cat_rental_request[end_date]">
  </label>

  <input type="submit" value="Submit">

  <input
   name="authenticity_token"
   type="hidden"
   value="<%= form_authenticity_token %>">
</form>

app/views/cats/_form.html.erb
<p>
  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%=cat.name %>">
</p>
<p>
  <label for="cat_age">Age</label>
  <input type="text" name="cat[age]" id="cat_age" value="<%=cat.age %>">
</p>
<p>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%="checked" if cat.sex == "M" %> >
  <label for="cat_sex_male">Male</label>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%="checked" if cat.sex == "F" %> >
  <label for="cat_sex_female">Female</label>
</p>
<p>
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color" selected="<%=cat.color%>">
    <option value=""></option>
    <% %w(Black Brown White Tabby Tie-Dye).each do |color| %>
      <option value="<%=color%>" <%="selected" if cat.color == color %>><%=color%></option>
    <% end %>
  </select>
</p>
<p>
  <label for="cat_birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id="cat_birth_date" value= <%=cat.birth_date%> >
</p>

app/views/cats/edit.html.erb
<form action= <%= cat_url @cat.id %>  method="post">
  <input type="hidden" name="_method" value="put">

  <%= render "form", cat: @cat %>

  <input type="submit" value="Update cat info">

  <input
   name="authenticity_token"
   type="hidden"
   value="<%= form_authenticity_token %>">
</form>

app/views/cats/index.html.erb
All the cats:
<ul>
<% @cats.each do |cat| %>
<li><%= link_to cat.name, cat %>
  <form action= <%= cat_url cat.id  %> method="POST">
    <input type = "submit" value="Delete cat">
    <input type="hidden" name="_method" value="DELETE">

    <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  </form>
</li>
<% end %>
</ul>

app/views/cats/new.html.erb
<form action= <%=cats_url%>  method="post">

  <%= render "form", cat: Cat.new %>

  <input type="submit" value="Create cat">

  <input
   name="authenticity_token"
   type="hidden"
   value="<%= form_authenticity_token %>">
</form>

app/views/cats/show.html.erb
All the stats:
<table>
<tr>
  <th>Name</th>
  <th>Birth Date</th>
  <th>Age</th>
  <th>Color</th>
  <th>Sex</th>
</tr>
<tr>
  <td><%=@cat.name%></td>
  <td><%=@cat.birth_date%></td>
  <td><%=@cat.age%></td>
  <td><%=@cat.color%></td>
  <td><%=@cat.sex%></td>
</tr>
</table>

<ul>
  <% @cat.requests.order(:start_date).each do |request| %>
  <li>Request #<%= request.id %> : <%= request.start_date %> through  <%= request.end_date %> STATUS: <%= request.status %>
    <% @owner_id = CatRentalRequest.find(request.id).cat.user_id %>
    <% if request.pending? && (current_user.id == @owner_id)%>
    <%= button_to "Approve", approve_cat_rental_request_url(request.id) %>
    <%= button_to "Deny", deny_cat_rental_request_url(request.id) %>
    <% end %>
  </li>
  <% end %>
</ul>

<%= button_to "Make a reservation for this cat", new_cat_rental_request_url, method: "get" %>
<%= button_to "Edit this cat", edit_cat_url, method: "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsProject</title>
  <%= csrf_meta_tags %>

</head>

<body>
<p class="flash"><%= flash.notice %></p>
<% if current_user.nil? %>
<form action= <%= new_session_url %> method="GET">
  <input type = "submit" value="Log In">
</form>
<% else %>
<%= "Hello #{current_user.user_name}"%>
<form action= <%= user_session_url current_user.id  %> method="POST">
  <input type = "submit" value="Log Out">
  <input type="hidden" name="_method" value="DELETE">
</form>
<% end %>

<%= debug params %>

<%= yield %>
<form action= <%= new_user_url %> method="GET">
  <input type = "submit" value="Register">
</form>

<form action= <%= new_cat_url %> method="GET">
  <input type = "submit" value="Add Cat">
</form>


<form action= <%= cats_url %> method="GET">
  <input type = "submit" value="Return to Cat Index">
</form>


</body>
</html>

app/views/users/_form.html.erb
<p>
  <label>User Name
  <input type="text" name="user[user_name]" value="<%=user.user_name %>">
  </label>
</p>
<p>
  <label>Password
  <input type="password" name="user[password]" value="<%=user.password %>">
  </label>
</p>

<input
 name="authenticity_token"
 type="hidden"
 value="<%= form_authenticity_token %>">

app/views/users/new.html.erb
<form action= <%=users_url%>  method="post">

  <%= render "form", user: User.new %>

  <input type="submit" value="Create user">
</form>